### ISSUE TITLE
Bad Request in Send 

### ISSUE THREAD

**Issue by bebenekmarcin** [bscheiman/BlockCypher#8]
When using latest https://www.nuget.org/packages/BlockCypher/1.0.22 package and calling 
Blockcypher.Send()  I'm getting following error:

System.Net.Http.HttpRequestException
Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BlockCypher.Blockcypher.<PostAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BlockCypher.Blockcypher.<Send>d__21.MoveNext()

After downloading sources from this repo I can send transaction to blockchain without any issues.

**Comment by ducchinhit** [comment]
Hi . can you help me. i get this source code and apply it. when i call send for test address input value by Faucet. i get this error. 
but when i call transaction hash with hash : 4ee1960dbec6f65664b49e91fa31bf37189b8323353770b5e1e33905cfeeece7  it is ok.
token : f355d1e37cc14728a95baa0254502404
address from : bcy1q4zqpz0aurfvffnr2p0qzk0mf233j9lh03xqhzp
address to : bcy1q5qwkymww724kj5zeg77ut4nk3kc9ghp673xzt7

"{\n  \"errors\": [\n    {\n      \"error\": \"Error validating generated transaction: Error running script for input 0 referencing 4ee1960dbec6f65664b49e91fa31bf37189b8323353770b5e1e33905cfeeece7 at 0: Script was NOT verified successfully.\"\n    }\n  ],\n  \"tx\": {\n    \"block_height\": -1,\n    \"block_index\": -1,\n    \"hash\": \"33d4944fcf1f84df028eece141bdb1bd09a66684bc27a77f602a34762c33a331\",\n    \"addresses\": [\n      \"bcy1q4zqpz0aurfvffnr2p0qzk0mf233j9lh03xqhzp\",\n      \"bcy1q5qwkymww724kj5zeg77ut4nk3kc9ghp673xzt7\"\n    ],\n    \"total\": 99990600,\n    \"fees\": 9400,\n    \"size\": 222,\n    \"vsize\": 141,\n    \"preference\": \"medium\",\n    \"relayed_by\": \"14.161.36.65\",\n    \"received\": \"2021-12-03T04:55:06.501341856Z\",\n    \"ver\": 1,\n    \"double_spend\": false,\n    \"vin_sz\": 1,\n    \"vout_sz\": 2,\n    \"confirmations\": 0,\n    \"inputs\": [\n      {\n        \"prev_hash\": \"4ee1960dbec6f65664b49e91fa31bf37189b8323353770b5e1e33905cfeeece7\",\n        \"output_index\": 0,\n        \"output_value\": 100000000,\n        \"sequence\": 4294967295,\n        \"addresses\": [\n          \"bcy1q4zqpz0aurfvffnr2p0qzk0mf233j9lh03xqhzp\"\n        ],\n        \"script_type\": \"pay-to-witness-pubkey-hash\",\n        \"age\": 54722,\n        \"witness\": [\n          \"3045022100fa6a9f961650ee1a9806410211b81e2e65b9ee4f30f554f8b10c544a14ee4ea40220538fa5786933e6ff1d26357ab698367e697b60da2e04e68102552c3eae806f5e\",\n          \"030a698b5faaa607fa98a9834acf6b4731edd86972f881dc32def94ea92fe4822c\"\n        ]\n      }\n    ],\n    \"outputs\": [\n      {\n        \"value\": 1000000,\n        \"script\": \"0014a01d626dcef2ab69505947bdc5d6768db0545c3a\",\n        \"addresses\": [\n          \"bcy1q5qwkymww724kj5zeg77ut4nk3kc9ghp673xzt7\"\n        ],\n        \"script_type\": \"pay-to-witness-pubkey-hash\"\n      },\n      {\n        \"value\": 98990600,\n        \"script\": \"0014a880113fbc1a5894cc6a0bc02b3f69546322feef\",\n        \"addresses\": [\n          \"bcy1q4zqpz0aurfvffnr2p0qzk0mf233j9lh03xqhzp\"\n        ],\n        \"script_type\": \"pay-to-witness-pubkey-hash\"\n      }\n    ]\n  },\n  \"tosign\": [\n    \"\"\n  ]\n}"

Thank you.
